---
- name: "zsh | Replace ~/.zshrc and ~/.zprofile with symlink to role files directory"
  become: true
  ansible.builtin.shell: |
    rm -rf "{{ ansible_user_dir }}/.zshrc" "{{ ansible_user_dir }}/.zprofile"
    ln -s "{{ role_path }}/files/.zshrc" "{{ ansible_user_dir }}/.zshrc"
    ln -s "{{ role_path }}/files/.zprofile" "{{ ansible_user_dir }}/.zprofile"

- name: Zsh | ubuntu | Install
  become: true
  apt:
    name: zsh
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Zsh | arch | Install
  pacman:
    name: zsh
    state: present
  when: ansible_distribution in ["Archlinux", "Manjaro"]
