---
- name: Download and install Kitty using curl
  ansible.builtin.shell: |
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: "{{ ansible_user_dir }}/.local/kitty.app"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

- name: Create a symbolic link to the Kitty executable
  become: true
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
    dest: "/usr/local/bin/kitty"
    state: link
    force: yes

- name: Add Kitty to the system PATH if using bash
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'export PATH="$PATH:{{ ansible_user_dir }}/.local/kitty.app/bin"'
    state: present
    create: yes
  when: ansible_env.SHELL in ['/bin/bash', '/usr/bin/bash']

- name: Add Kitty to the system PATH if using zsh
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: 'export PATH="$PATH:{{ ansible_user_dir }}/.local/kitty.app/bin"'
    state: present
    create: yes
  when: ansible_env.SHELL in ['/bin/zsh', '/usr/bin/zsh']
