---
- name: "Tmux | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: tmux_distribution_config

- name: "Tmux | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | ubuntu | Install tmux"
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: "Tmux | arch | Install tmux"
  community.general.pacman:
    name: tmux
    state: present
  become: true
  when: ansible_distribution in ["ArchLinux", "Manjaro"]

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: tmux
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
