---
- name: "Neovim | Create Config folder"
  become: true
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim | Replace ~/.config/nvim with symlink to role files directory"
  become: true
  ansible.builtin.shell: |
    rm -rf "{{ ansible_user_dir }}/.config/nvim"
    ln -s "{{ role_path }}/files" "{{ ansible_user_dir }}/.config/nvim"

- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present

- name: "Neovim | {{ ansible_distribution }} | Install"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install Neovim on Arch-based systems
  pacman:
    name: neovim
    state: present
  when: ansible_distribution in ["Archlinux", "Manjaro"]
